version: '3.4'
services:
  bot:
    build: .
    network_mode: 'host'
    container_name: 'santa_bot'
    volumes: 
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: python3 main.py
    restart: 'unless-stopped'
